/**
 * sysex-enums.js - VL3X Enum Definitions
 * 
 * Maps enum names to their value arrays for parameter display.
 * Synced from data.json (gold standard).
 */

export const ENUMS = {
  "hardtune_style": [
    "POP",
    "COUNTRY GLISS",
    "CORRECT NATURAL",
    "CORRECT CHROMATIC",
    "GENDER BENDER",
    "ROBOT",
    "PEDAL"
  ],
  "amp_style": [
    "ACOUSTIC",
    "CLEAN BRIT",
    "CALI CLEAN",
    "UK CLEAN",
    "DEEP CLEAN",
    "BRIGHT SWITCH",
    "WARM",
    "LITTLE THING",
    "CHICKEN PICKER",
    "BRIT OD",
    "AC CRUNCH",
    "CHUNKY BRIT",
    "LIL CHAMPION",
    "CHIME DRIVE",
    "2X12 COMBO",
    "4X12 CRUNCH",
    "SWAMPTONE",
    "NASALTONE",
    "BROWN",
    "SCOOPED",
    "METALLIC",
    "TC DARK MATTER",
    "OD PEDAL",
    "DARK OD PEDAL",
    "DISTORTION PEDAL",
    "BODYREZ 1",
    "BODYREZ 2",
    "BODYREZ 3",
    "BODYREZ 4",
    "BODYREZ 5"
  ],
  "harmony_style": [
    "HIGH",
    "LOW",
    "HIGH & LOW",
    "HIGH & HIGHER",
    "LOW & LOWER",
    "HIGHER & LOWER",
    "BASS & HIGH",
    "GOSPEL CHOIR",
    "UPPER CHOIR",
    "LOWER CHOIR",
    "HIGH & PEDAL + O",
    "HIGH & SCALE -3RD",
    "LOW & FIXED -12",
    "LOWER & PEDAL -5",
    "HIGH & SHIFT +7",
    "BIG MIXED MODE",
    "HIGH & LOW & PEDALS",
    "PEDAL OCTAVE CHOIR",
    "PEDAL BASS GROUP",
    "LOWER MONKS",
    "UPPER MONKS",
    "FIFTH UP",
    "-4TH DOWN",
    "OCTAVE UP GROUP",
    "OCTAVE DOWN GROUP",
    "HARMONIZED NOTES",
    "TIGHT NOTES",
    "MALE NOTES",
    "FEMALE NOTES",
    "4CHNL NOTES"
  ],
  "human_style": [
    "OFF",
    "TIGHT",
    "NATURAL",
    "RELAXED",
    "LOOSE",
    "RANDOM",
    "TIME & PITCH"
  ],
  "vibrato_style": [
    "OFF",
    "EASY",
    "BALLAD",
    "JAZZ",
    "DELICATE",
    "FLUTTER",
    "MOURNFUL",
    "OLD TIME"
  ],
  "natplay_input": {
    "0": "AUTOSENSE",
    "1": "GUITAR",
    "2": "MIDI",
    "3": "AUX/MON",
    "4": "ROOMSENSE",
    "5": "TRACK/USB"
  },
  "tuning": [
    "EQUAL",
    "JUST",
    "BARBERSHOP"
  ],
  "voice_mode": [
    "OFF",
    "NATURAL PLAY",
    "SCALE",
    "SHIFT",
    "PEDAL",
    "FIXED"
  ],
  "voice_voicing": [
    "2 OCTAVE DOWN",
    "OCTAVE DOWN",
    "BASS",
    "LOWER",
    "LOW",
    "UNISON",
    "HIGH",
    "HIGHER",
    "OCTAVE UP"
  ],
  "double_style": [
    "1 VOICE TIGHT",
    "1 VOICE LOOSE",
    "2 VOICES WIDE",
    "4 VOICES TIGHT",
    "4 VOICES WIDE",
    "MIXED DOUBLES",
    "4 VOICES MONO",
    "OCTAVE DOWN DOUBLE",
    "OCTAVE UP DOUBLE",
    "OCTAVE DOWN GROUP",
    "OCTAVE UP GROUP",
    "MIXED OCTAVES"
  ],
  "choir_style": [
    "SMALL 1",
    "SMALL 2",
    "MEDIUM 1",
    "MEDIUM 2",
    "MEDIUM 3",
    "LARGE",
    "LOOSE",
    "EUROPEAN",
    "AMERICAN",
    "TIGHT",
    "PITCHY",
    "SPEAKING",
    "CHAOS"
  ],
  "umod_style_voice": [
    "CHOPPER",
    "TREMOLO",
    "GENDER MOD",
    "SOFT PANNER",
    "HARD PANNER",
    "GENDER RANDOM",
    "SYNCOPATED CHOP",
    "SLOWDOWN",
    "SPACE GENDER",
    "GRANULAR",
    "FLUTTER PAN"
  ],
  "umod_waveform": [
    "SQUARE",
    "TRIANGLE",
    "SINE",
    "SAWTOOTH UP",
    "SAWTOOTH DOWN",
    "SAMPLE AND HOLD",
    "SIXTEENTH ACC",
    "8TH & 16THS",
    "SYNCOPATED",
    "SYNCOPATED ACC",
    "16TH TO 8THS",
    "SWUNG EIGHTS",
    "STRAIGHT EIGTHS",
    "EIGHTH TRIPLETS",
    "LATINO ACCENTS",
    "LATINO",
    "8THT & 2T",
    "MILITARY",
    "BHANGRA",
    "SLOWDOWN",
    "SPEEDUP",
    "3/4 TIME 1",
    "3/4 TIME 2"
  ],
  "umod_style_guitar": [
    "CORONA CHORUS 12:00",
    "CORONA CHORUS FAST",
    "CORONA CHORUS SLOW",
    "VORTEX FLANGER 12:00",
    "VORTEX FLANGER FAST",
    "SILKY DETUNE",
    "MEDIUM DETUNE",
    "MONO CHORUS",
    "FAST ROTOR",
    "FLANGER",
    "FLANGE FEEDBACK",
    "FLANGE NEGATIVE",
    "MONO FLANGE",
    "SOFT FLANGE"
  ],
  "delay_style_voice": [
    "FLASHBACK 2290",
    "FLASHBACK ANALOG",
    "FLASHBACK TAPE",
    "FLASHBACK LO-FI",
    "FLASHBACK SLAP",
    "EDGE-Y MOD",
    "ANALOG MODULAR",
    "QUARTER",
    "DOTTED 1/8",
    "PING-PONG",
    "PING-PONG FX",
    "MULTI-TAP",
    "300MS",
    "LONG & THIN",
    "REVERB TANK"
  ],
  "delay_division": [
    "8X1/4",
    "7X1/4",
    "6X1/4",
    "4X1/4",
    "1/2 DOT",
    "1/2",
    "1/2 TRIP",
    "1/4 DOT",
    "1/4 2-DOT",
    "1/4",
    "1/4 TRIP",
    "1/8 DOT",
    "1/8",
    "1/8 TRIP",
    "1/16 DOT",
    "1/16",
    "1/16 TRIP",
    "1/32 DOT",
    "1/32",
    "1/32 TRIP"
  ],
  "delay_style_guitar": [
    "HALF",
    "QUARTER",
    "EIGTH",
    "TRIPLET",
    "DOTTED 1/8",
    "DOTTED 1/4",
    "1/4 TRIPLET",
    "SIXTEENTH",
    "PING PONG 1",
    "PING PONG 2",
    "PING PONG 3",
    "MULTITAP 1",
    "MULTITAP 2",
    "MULTITAP 3",
    "MULTITAP 4",
    "MULTITAP 5",
    "MULTITAP 6",
    "CLASSIC SLAP",
    "SET TIME"
  ],
  "delay_filter_style": [
    "DIGITAL",
    "TAPE",
    "ANALOG",
    "RADIO",
    "MEGA PHONE",
    "CELL PHONE",
    "LO-FI",
    "HI CUT 1",
    "HI CUT 2",
    "HI CUT 3",
    "LO CUT 1",
    "LO CUT 2",
    "LO CUT 3"
  ],
  "reverb_style_voice": [
    "HALL OF FAME AMB",
    "HALL OF FAME TILE",
    "HALL OF FAME ROOM",
    "HALL OF FAME LOFI",
    "HALL OF FAME SPRING",
    "HALL OF FAME PLATE",
    "HALL OF FAME HALL",
    "HALL OF FAME CHURCH",
    "WOOL AMBIENCE",
    "MICROSPACE SLAP",
    "ALMOST SLAP",
    "COZY CORNER",
    "AMBIENT SCATTER",
    "LIBRARY",
    "DARK ROOM",
    "BOUNCY ROOM",
    "STUDIO ROOM",
    "DARK BLOOM",
    "SHOWER STALL",
    "SNAPPY ROOM",
    "MUSIC CLUB",
    "WAREHOUSE",
    "SCATTER",
    "BRIGHT & LIVELY",
    "DARK CHAMBER",
    "THIN PLATE",
    "QUICK PLATE",
    "SHORT SPRING",
    "REAL PLATE",
    "JAZZ PLATE",
    "BROADWAY HALL",
    "AMSTERDAM HALL",
    "WOODEN CHAMBER",
    "DOME CHAPEL",
    "REFLECTION PLATE",
    "SHIMMER MOD",
    "BASKETBALL COURT",
    "SOFT HALL",
    "REAL PLATE LONG",
    "SPRING-ISH",
    "BRIGHT PLATE",
    "MUSEUM",
    "RINGY",
    "BRIGHT CHAMBER",
    "ST.JOSEPH CHURCH",
    "INDOOR ARENA",
    "SMOOTH PLATE",
    "THIN SPRING",
    "HOCKEY ARENA",
    "FULL SPRING",
    "LONG BRIGHT MOD",
    "LONG SPRING"
  ],
  "reverb_style_guitar": [
    "HALL OF FAME AMB",
    "HALL OF FAME TILE",
    "HALL OF FAME ROOM",
    "HALL OF FAME LOFI",
    "HALL OF FAME SPRING",
    "HALL OF FAME PLATE",
    "HALL OF FAME HALL",
    "HALL OF FAME CHURCH",
    "WOOL AMBIENCE",
    "MICROSPACE SLAP",
    "ALMOST SLAP",
    "COZY CORNER",
    "AMBIENT SCATTER",
    "LIBRARY",
    "DARK ROOM",
    "BOUNCY ROOM",
    "STUDIO ROOM",
    "DARK BLOOM",
    "SHOWER STALL",
    "SNAPPY ROOM",
    "MUSIC CLUB",
    "WAREHOUSE",
    "SCATTER",
    "BRIGHT & LIVELY",
    "DARK CHAMBER",
    "THIN PLATE",
    "QUICK PLATE",
    "SHORT SPRING",
    "REAL PLATE",
    "JAZZ PLATE",
    "BROADWAY HALL",
    "AMSTERDAM HALL",
    "WOODEN CHAMBER",
    "DOME CHAPEL",
    "REFLECTION PLATE",
    "BASKETBALL COURT",
    "SOFT HALL",
    "REAL PLATE LONG",
    "SPRING-ISH",
    "BRIGHT PLATE",
    "MUSEUM",
    "RINGY",
    "BRIGHT CHAMBER",
    "ST.JOSEPH CHURCH",
    "INDOOR ARENA",
    "SMOOTH PLATE",
    "THIN SPRING",
    "HOCKEY ARENA",
    "FULL SPRING",
    "LONG BRIGHT MOD",
    "LONG SPRING"
  ],
  "transducer_style": [
    "DIGITAL",
    "TAPE",
    "ANALOG",
    "RADIO",
    "MEGA PHONE",
    "CELL PHONE",
    "LO-FI",
    "HI CUT 1",
    "HI CUT 2",
    "HI CUT 3",
    "LO CUT 1",
    "LO CUT 2",
    "LO CUT 3"
  ],
  "drive_style": [
    "BOOST",
    "DRIVE",
    "DRIVE & BOOST"
  ],
  "drive_substyle": [
    "SATURATION 1",
    "SATURATION 2",
    "SATURATION 3",
    "OVERDRIVE 1",
    "OVERDRIVE 2",
    "OVERDRIVE 3",
    "OVERDRIVE 4",
    "OVERDRIVE 5",
    "DISTORTION 1",
    "DISTORTION 2",
    "DISTORTION 3",
    "DISTORTION 4",
    "FUZZ 1",
    "FUZZ 2",
    "FUZZ 3"
  ],
  "comp_style": [
    "SUBTLE TUBE",
    "SUBTLE SUSTAIN",
    "SUSTAIN ATTACK",
    "SUSTAIN POP",
    "PUMPING"
  ],
  "wah_style": [
    "CLASSIC WAH",
    "REZ WAH",
    "FILTER WAH",
    "FAST RES TOUCH",
    "RESONANT TOUCH",
    "SLOW RES TOUCH",
    "FAST SOFT TOUCH",
    "SLOW SOFT TOUCH",
    "FILTER TREMOLO",
    "AUTO FILTER"
  ],
  "octaver_style": [
    "OCTAVE DOWN",
    "MIX OCTAVE DOWN",
    "FOURTH DOWN",
    "FIFTH UP",
    "OCTAVE UP",
    "2 OCT DOWN"
  ],
  "rhythm_style_guitar": [
    "CHOPPER",
    "TREMOLO",
    "SOFT PANNER",
    "HARD PANNER",
    "SOFT SAW",
    "SAW PANNER",
    "CHOP SAW"
  ],
  "synth_style": [
    "SYNTH 1",
    "SYNTH 2",
    "SYNTH HARMONY 1",
    "SYNTH HARMONY 2",
    "BASS VOCODE",
    "SYNTH 3",
    "SYNTH 4",
    "SYNTH 5",
    "GUITAR TALKBOX",
    "GUITAR TALKBOX 2",
    "SYNTH 6",
    "SYNTH 7",
    "PULSE DOUBLE"
  ],
  "stutter_style": [
    "STUTTER",
    "REVERSE SAMPLE",
    "FORWARD SAMPLE",
    "EIGTH SAMPLE"
  ],
  "key_source": [
    "FOLLOW HARMONY",
    "MANUAL / CUSTOM",
    "ROBOT MODE",
    "PEDAL MODE"
  ],
  "scale": [
    "MAJOR",
    "MINOR NAT",
    "MINOR HARM",
    "MINOR ASC",
    "CHROMATIC",
    "CUSTOM"
  ],
  "key": [
    "C",
    "C#",
    "D",
    "D#",
    "E",
    "F",
    "F#",
    "G",
    "G#",
    "A",
    "A#",
    "B"
  ],
  "buttonmap_function": [
    "STEP",
    "PITCH CORR",
    "ALL MUTE",
    "UMOD",
    "DELAY",
    "REVERB",
    "VOC HIT",
    "DOUBLE",
    "HARMONY",
    "TRANSDUCER",
    "HARDTUNE",
    "RHYTHMIC",
    "STUTTER",
    "CHOIR",
    "SYNTH",
    "HARM HOLD",
    "SET KEY",
    "TAP TEMPO",
    "BYPASS",
    "G UMOD",
    "G DELAY",
    "G REVERB",
    "G HIT",
    "G COMP",
    "G DRIVE",
    "G AMP",
    "G RHYTHM",
    "G OCTAVER",
    "G WAH",
    "G MUTE",
    "ALL HIT",
    "TUNER",
    "LOOPER",
    "LOOP INPUT",
    "1BTN LOOPER",
    "LPLAY/REC",
    "LSTOP/ERASE",
    "LOOP UNDO",
    "LERASE ALL",
    "LOOP TRIG A",
    "LOOP TRIG B",
    "LOOP TRIG C",
    "LOOP TRIG D",
    "LOOP TRIG E",
    "LOOP TRIG F",
    "LOOP TRIG G",
    "LOOP TRIG H",
    "TRACK START",
    "TRACK STOP",
    "TRACK FWD",
    "TRACK BACK",
    "SEQ REC",
    "SEQ UNDO",
    "SPARE1",
    "SPARE2",
    "SPARE3"
  ],
  "expr_pedal_function": [
    "OFF",
    "LEAD OCT DOWN",
    "LEAD OCT UP",
    "HARM OCT DOWN",
    "HARM OCT UP",
    "HARM & DOUBLE LEVEL",
    "DELAY/REVERB LEVEL",
    "HARMONY LEVEL",
    "DOUBLE LEVEL",
    "VOC UMOD LEVEL",
    "VOC DELAY LEVEL",
    "VOC REVERB LEVEL",
    "SYNTH LEVEL",
    "LEAD LEVEL",
    "VOC UMOD/DLY/REV LVL",
    "VOC LEVEL",
    "AUX LEVEL",
    "VOC DELAY SENDS",
    "VOC REVERB SENDS",
    "RHYTHMIC DEPTH",
    "RHYTHMIC DIVISION",
    "STUTTER DIV",
    "GTR UMOD LEVEL",
    "GTR DELAY LEVEL",
    "GTR REVERB LEVEL",
    "GTR DELAY REVERB",
    "GTR RHYTHMIC DEPTH",
    "GTR RHYTHMIC DIV",
    "GTR AMP POST GAIN",
    "GTR AMP PRE GAIN",
    "GTR LEVEL",
    "GTR PAN",
    "LOOPER LEVEL",
    "HEADPHONE LEVEL",
    "GTR DELAY SEND",
    "GTR REVERB SEND",
    "SMART WAH",
    "CONTEXT DELAY SEND"
  ],
  "buttonmap_mode": [
    "LATCHED",
    "MOMENTARY"
  ],
  "mic_type": [
    "DYNAMIC",
    "CONDENSOR",
    "MP-75",
    "E835-FX",
    "MP-76",
    "USB"
  ],
  "on_off": [
    "OFF",
    "ON"
  ],
  "genre": [
    "ALL",
    "FAVOURITE",
    "SHOWCASE",
    "SONGS & ARTISTS",
    "POP",
    "ROCK",
    "BLUES",
    "ALTERNATIVE",
    "COUNTRY",
    "HIP HOP/RAP",
    "EDM",
    "ECHO",
    "DOUBLING",
    "REVERB",
    "HARMONY",
    "HARDTUNE",
    "MEGAPHONE",
    "EXTREME",
    "CHARACTER",
    "CLEAN GUITAR",
    "OVERDRIVE GUITAR",
    "ACOUSTIC GUITAR"
  ],
  "looper_track": [
    "TRACK A",
    "TRACK B",
    "TRACK C",
    "TRACKS A + B",
    "TRACKS A + C"
  ],
  "output_routing": [
    "STEREO",
    "MONO",
    "DUAL MONO"
  ],
  "usb_output_mode": [
    "STEREO",
    "DAW TRACKING",
    "DAW INSERT"
  ],
  "pan": [
    "OFF",
    "BOTH",
    "LEFT",
    "RIGHT"
  ],
  "shift_interval": [
    "-24 SEMITONES",
    "-23 SEMITONES",
    "-22 SEMITONES",
    "-21 SEMITONES",
    "-20 SEMITONES",
    "-19 SEMITONES",
    "-18 SEMITONES",
    "-17 SEMITONES",
    "-16 SEMITONES",
    "-15 SEMITONES",
    "-14 SEMITONES",
    "-13 SEMITONES",
    "-12 SEMITONES",
    "-11 SEMITONES",
    "-10 SEMITONES",
    "-9 SEMITONES",
    "-8 SEMITONES",
    "-7 SEMITONES",
    "-6 SEMITONES",
    "-5 SEMITONES",
    "-4 SEMITONES",
    "-3 SEMITONES",
    "-2 SEMITONES",
    "-1 SEMITONES",
    "UNISON",
    "+1 SEMITONES",
    "+2 SEMITONES",
    "+3 SEMITONES",
    "+4 SEMITONES",
    "+5 SEMITONES",
    "+6 SEMITONES",
    "+7 SEMITONES",
    "+8 SEMITONES",
    "+9 SEMITONES",
    "+10 SEMITONES",
    "+11 SEMITONES",
    "+12 SEMITONES",
    "+13 SEMITONES",
    "+14 SEMITONES",
    "+15 SEMITONES",
    "+16 SEMITONES",
    "+17 SEMITONES",
    "+18 SEMITONES",
    "+19 SEMITONES",
    "+20 SEMITONES",
    "+21 SEMITONES",
    "+22 SEMITONES",
    "+23 SEMITONES",
    "+24 SEMITONES"
  ],
  "scale_interval": [
    "-2 OCTAVES",
    "-1 OCTAVE -7TH",
    "-1 OCTAVE -6TH",
    "-1 OCTAVE -5TH",
    "-1 OCTAVE -4TH",
    "-1 OCTAVE -3RD",
    "-1 OCTAVE -2ND",
    "-1 OCTAVE",
    "-7TH",
    "-6TH",
    "-5TH",
    "-4TH",
    "-3RD",
    "-2ND",
    "UNISON",
    "+2ND",
    "+3RD",
    "+4TH",
    "+5TH",
    "+6TH",
    "+7TH",
    "+1 OCTAVE",
    "+1 OCTAVE +2ND",
    "+1 OCTAVE +3RD",
    "+1 OCTAVE +4TH",
    "+1 OCTAVE +5TH",
    "+1 OCTAVE +6TH",
    "+1 OCTAVE +7TH",
    "+2 OCTAVES"
  ],
  "rhythm_division": [
    "1/4",
    "1/4 TRIP",
    "1/8 DOT",
    "1/8",
    "1/8 TRIP",
    "1/16 DOT",
    "1/16",
    "1/16 TRIP",
    "1/32 DOT",
    "1/32",
    "1/32 TRIP"
  ],
  "harmony_mode": [
    "NATURALPLAY",
    "SCALE",
    "SHIFT",
    "DRONE",
    "FIXED",
    "OFF"
  ],
  "micromod_style_voice": [
    "MICRO1",
    "MICRO2",
    "MICRO3",
    "CHORUS1",
    "CHORUS2",
    "CHORUS3",
    "DETUNE1",
    "DETUNE2",
    "DETUNE3",
    "FLANGE1",
    "FLANGE2",
    "FLANGE3",
    "ROTOR1",
    "ROTOR2",
    "ROTOR3",
    "TREML",
    "TREMR",
    "VIBSHORT",
    "VIBMED",
    "VIBLONG",
    "DIMENSION",
    "PITCH1",
    "OFF"
  ],
  "micromod_style_guitar": [
    "CORONA CHORUS 12:00",
    "CORONA CHORUS FAST",
    "CORONA CHORUS SLOW",
    "VORTEX FLANGER 12:00",
    "VORTEX FLANGER FAST",
    "SILKY DETUNE",
    "MEDIUM DETUNE",
    "MONO CHORUS",
    "FAST ROTOR",
    "FLANGER",
    "FLANGE FEEDBACK",
    "FLANGE NEGATIVE",
    "MONO FLANGE",
    "SOFT FLANGE"
  ],
  "guitar_comp_style": [
    "SUBTLE TUBE",
    "SUBTLE SUSTAIN",
    "SUSTAIN ATTACK",
    "SUSTAIN POP",
    "PUMPING"
  ],
  "correct_scale": [
    "MAJOR",
    "MINOR NAT",
    "MINOR HARM",
    "MINOR ASC",
    "CHROMATIC",
    "CUSTOM (NOTE ENABLE)"
  ],
  "hit_control": [
    "OFF",
    "ON",
    "HIT ON",
    "HIT OFF"
  ],
  "button_function": [
    "UMOD",
    "DELAY",
    "REVERB",
    "VOC HIT",
    "DOUBLE",
    "HARMONY",
    "TRANSDUCER",
    "HARDTUNE",
    "RHYTHMIC",
    "STUTTER",
    "CHOIR",
    "SYNTH",
    "HARM HOLD",
    "SET KEY",
    "TAP TEMPO",
    "BYPASS",
    "G UMOD",
    "G DELAY",
    "G REVERB",
    "G HIT",
    "G COMP",
    "G DRIVE",
    "G AMP",
    "G RHYTHM",
    "G OCTAVER",
    "G WAH",
    "G MUTE",
    "ALL HIT",
    "TUNER",
    "LOOPER",
    "LOOP INPUT",
    "1BTN LOOPER",
    "LPLAY/REC",
    "LSTOP/ERASE",
    "LOOP UNDO",
    "LERASE ALL",
    "LOOP TRIG A",
    "LOOP TRIG B",
    "LOOP TRIG C",
    "LOOP TRIG D",
    "LOOP TRIG E",
    "LOOP TRIG F",
    "LOOP TRIG G",
    "LOOP TRIG H",
    "TRACK START",
    "TRACK STOP",
    "TRACK FWD",
    "TRACK BACK",
    "SEQ REC",
    "SEQ UNDO",
    "SPARE1",
    "SPARE2",
    "SPARE3",
    "STEP",
    "PITCH CORR",
    "ALL MUTE"
  ],
  "button_modifier": [
    "LATCHED",
    "MOMENTARY"
  ],
  "rhythmic_style": [
    "TREMOLO",
    "FILTER 1",
    "FILTER 2",
    "FILTER 3",
    "PAN 1",
    "PAN 2",
    "VOLUME 1",
    "VOLUME 2",
    "VOLUME 3",
    "VOCODER",
    "OFF"
  ],
  "delay_source": [
    "MANUAL",
    "TEMPO"
  ],
  "delay_filter": [
    "OFF",
    "BRIGHT",
    "ANALOG",
    "DARK",
    "LO-FI"
  ],
  "note_division": [
    "8 X 1/4",
    "7 X 1/4",
    "6 X 1/4",
    "4 X 1/4",
    "1/2 DOT",
    "1/2",
    "1/2 TRIP",
    "1/4 DOT",
    "1/4 2-DOT",
    "1/4",
    "1/4 TRIP",
    "1/8 DOT",
    "1/8 DOT",
    "1/8 TRIP",
    "1/16 DOT",
    "1/16",
    "1/16 TRIP",
    "1/32 DOT",
    "1/32",
    "1/32 TRIP"
  ],
  "button_mode": [
    "MOMENTARY",
    "LATCHED"
  ],
  "rhythmic_target": [
    "LEVEL",
    "PAN",
    "FILTER"
  ],
  "waveform": [
    "SQUARE",
    "TRIANGLE",
    "SINE",
    "SAWTOOTH UP",
    "SAWTOOTH DOWN"
  ],
  "amp_mode": [
    "CLEAN",
    "TUBE",
    "CRUNCH",
    "HIGH GAIN"
  ],
  "reverb_type_guitar": [
    "AMBIENT",
    "TILE",
    "ROOM",
    "LOFI",
    "SPRING",
    "PLATE",
    "HALL",
    "CHURCH",
    "MOD"
  ],
  "wah_order": [
    "2ND",
    "4TH"
  ],
  "wah_subtype": [
    "CLASSIC",
    "TOUCH",
    "AUTOWAH"
  ],
  "stutter_direction": [
    "FORWARD",
    "REVERSE"
  ],
  "stutter_path": [
    "PRE",
    "POST"
  ],
  "stutter_capture": [
    "START",
    "FULL",
    "END"
  ],
  "wah_response": [
    "100 MS",
    "200 MS",
    "300 MS",
    "400 MS",
    "500 MS",
    "600 MS",
    "700 MS",
    "800 MS",
    "900 MS",
    "1000 MS",
    "2000 MS",
    "3000 MS"
  ]
};
